FROM ruby:3.0.2-alpine
RUN apk add \
    build-base \
    postgresql-dev \
    tzdata \
    nodejs
RUN apt-get update && apt-get install -y nodejs
WORKDIR /app
COPY Gemfile .
RUN bundle install
COPY . /app
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]